name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: windows-latest # O el sistema operativo que uses para construir
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Reemplaza con tu versión de Java si es diferente
          distribution: 'temurin' # Cambia a temurin
      - name: Build with Maven # O tu comando de construcción
        run: mvn clean package
        
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    needs: build # Asegura que el job 'build' se complete primero
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectKey=pabno5_Software-Qualitys # Asegúrate de que coincida con tu Project Key en SonarQube
            -Dsonar.sources=.
            -Dsonar.java.binaries=./target/classes # Ajusta la ruta a tus clases compiladas
